version: '3.8'

services:

  nginx:
    build: ./nginx
    restart: always
    environment:
      TZ: Asia/Taipei
    hostname: nginx
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - frontend
      - efk
    depends_on:
      - redmine
    ports:
      - "80:80"
      - "443:443"
      - "5601:5601"

  redmine:
    build: ./redmine
    container_name: myredmine
    restart: always
    volumes:
      - ./data/redmine/files:/usr/src/redmine/files
      - ./data/redmine/plugins:/usr/src/redmine/plugins
    env_file: .env
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PORT: 5432
      REDMINE_DB_USERNAME: ${DB_USERNAME}
      REDMINE_DB_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Taipei
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: redmine.access
    networks:
      - frontend
      - backend
      - logger
    depends_on:
      - db
      - fluentd

  db:
    image: postgres:13.3-alpine
    container_name: postre13-3
    restart: always
    volumes:
      - ./data/redmine/postgre:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Taipei

  fluentd:
    build: ./fluentd
    container_name: fluentd_redmine
    restart: on-failure
    environment:
      TZ: Asia/Taipei
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - logger
      - efk
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch_redmine
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - TZ=Asia/Taipei
      - bootstrap.memory_lock=true
    expose:
      - "9200"
    networks:
      - efk

  kibana:
    container_name: kibana_redmine
    image: kibana:7.10.1
    restart: on-failure
    environment:
      TZ: Asia/Taipei
    depends_on:
      - elasticsearch
    networks:
      - efk

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  logger:
    driver: bridge
  efk:
    driver: bridge