version: '3.8'

services:

  nginx:
    build: ./nginx
    restart: always
    environment:
      TZ: Asia/Taipei
    hostname: nginx
    networks:
      - frontend
    depends_on:
      - redmine
    ports:
      - "80:80"
      - "443:443"

  redmine:
    image: redmine:4.2.1
    container_name: myredmine
    restart: always
    volumes:
      - ./data/redmine/files:/usr/src/redmine/files
      - ./data/redmine/plugins:/usr/src/redmine/plugins
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PORT: 5432
      REDMINE_DB_USERNAME: ${DB_USERNAME}
      REDMINE_DB_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Taipei"
    networks:
      - frontend
      - backend
    depends_on:
      - db

  db:
    image: postgres:13.3-alpine
    container_name: postre13-3
    user: postgres
    restart: always
    volumes:
      - ./data/redmine/postgre:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Taipei"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge