CREATE ROLE redmine LOGIN ENCRYPTED PASSWORD 'wsaVx1+P8BRJTxv8' NOINHERIT VALID UNTIL 'infinity';
CREATE DATABASE redmine WITH ENCODING='UTF8' OWNER=redmine;
GRANT ALL PRIVILEGES ON DATABASE redmine TO redmine;